"""feat: model rewrite to have do not care in preferences

Revision ID: 7eb01cbd022e
Revises: 
Create Date: 2026-04-19 19:15:43.221560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb01cbd022e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('occupation', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('profile_photo_path', sa.String(length=256), nullable=True),
    sa.Column('target_country', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('connection_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_a_id', sa.Integer(), nullable=False),
    sa.Column('user_b_id', sa.Integer(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_radius_miles', sa.Integer(), nullable=True),
    sa.Column('preferred_gender', sa.String(length=32), nullable=True),
    sa.Column('preferred_age_min', sa.Integer(), nullable=True),
    sa.Column('preferred_age_max', sa.Integer(), nullable=True),
    sa.Column('my_cleanliness', sa.Integer(), nullable=True),
    sa.Column('pref_cleanliness', sa.Integer(), nullable=True),
    sa.Column('cleanliness_is_strict', sa.Boolean(), nullable=True),
    sa.Column('cleanliness_do_not_care', sa.Boolean(), nullable=True),
    sa.Column('my_sleep_schedule', sa.Integer(), nullable=True),
    sa.Column('pref_sleep_schedule', sa.Integer(), nullable=True),
    sa.Column('sleep_is_strict', sa.Boolean(), nullable=True),
    sa.Column('sleep_schedule_do_not_care', sa.Boolean(), nullable=True),
    sa.Column('my_noise_tolerance', sa.Integer(), nullable=True),
    sa.Column('pref_noise_tolerance', sa.Integer(), nullable=True),
    sa.Column('noise_is_strict', sa.Boolean(), nullable=True),
    sa.Column('noise_tolerance_do_not_care', sa.Boolean(), nullable=True),
    sa.Column('my_guests_frequency', sa.Integer(), nullable=True),
    sa.Column('pref_guests_frequency', sa.Integer(), nullable=True),
    sa.Column('guests_is_strict', sa.Boolean(), nullable=True),
    sa.Column('guests_frequency_do_not_care', sa.Boolean(), nullable=True),
    sa.Column('my_smoking', sa.Integer(), nullable=True),
    sa.Column('pref_smoking', sa.Integer(), nullable=True),
    sa.Column('smoking_is_strict', sa.Boolean(), nullable=True),
    sa.Column('smoking_do_not_care', sa.Boolean(), nullable=True),
    sa.Column('my_drinking', sa.Integer(), nullable=True),
    sa.Column('pref_drinking', sa.Integer(), nullable=True),
    sa.Column('drinking_is_strict', sa.Boolean(), nullable=True),
    sa.Column('drinking_do_not_care', sa.Boolean(), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('budget_is_strict', sa.Boolean(), nullable=True),
    sa.Column('has_pets', sa.Boolean(), nullable=True),
    sa.Column('pref_no_pets', sa.Boolean(), nullable=True),
    sa.Column('pets_is_strict', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    op.drop_table('messages')
    op.drop_table('matches')
    op.drop_table('connection_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
